[package]
name = "time_and_sales_deliver"
version = "0.1.0"
edition = "2018"
authors = ["dogwood008"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "1.0.0"
env_logger = "0.7"
futures = "0.3"